export const environment = {
  production: true,
  APIURL: "http://localhost:63177",
  ADMINISTRATOR_ROLE: "ADMINISTRATOR",
  PORT_ROLE: "PORT_OPERATOR",
  TRANSPORTER_ROLE: "TRANSPORTER",
  YARD_ROLE: "YARD_OPERATOR",
  SALESMAN_ROLE: "SALESMAN",
  CAR_TYPE: "0",
  TRUCK_TYPE: "1",
  SUV_TYPE: "2",
  VAN_TYPE: "3",
  MINI_VAN_TYPE: "4"
};
