//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleTracking_Data_DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VehicleTracking_Data_DataAccess.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se pudo encontrar al {0} con ID {1}..
        /// </summary>
        internal static string CouldNotFindElement {
            get {
                return ResourceManager.GetString("CouldNotFindElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el {0} &quot;{1}&quot; no se encuentra registrado en el sistema..
        /// </summary>
        internal static string CouldNotFindField {
            get {
                return ResourceManager.GetString("CouldNotFindField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: el elemento recibido a eliminar no se encontraba registrado en el sistema..
        /// </summary>
        internal static string CouldNotRemoveElement {
            get {
                return ResourceManager.GetString("CouldNotRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento inválido recibido: no se encuentra registrado en el sistema..
        /// </summary>
        internal static string ElementDoesNotExist {
            get {
                return ResourceManager.GetString("ElementDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible completar la acción. El {0} ingresado ya se encuentra registrado en el sistema..
        /// </summary>
        internal static string FieldMustBeUnique {
            get {
                return ResourceManager.GetString("FieldMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se recibió un usuario inválido para el registro del histórico de una cierta acción. Verifique que éste cuenta con los privilegios suficientes para ella..
        /// </summary>
        internal static string InvalidUserRoleForLogging {
            get {
                return ResourceManager.GetString("InvalidUserRoleForLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se recibió una ID nula de elemento a eliminar..
        /// </summary>
        internal static string NullIDRecieved {
            get {
                return ResourceManager.GetString("NullIDRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se recibió una referencia a objeto nula con la que interactuar en un Repository..
        /// </summary>
        internal static string NullObjectRecieved {
            get {
                return ResourceManager.GetString("NullObjectRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible completar la acción. Ya existe otra subzona registrada con el mismo nombre dentro de la misma zona..
        /// </summary>
        internal static string SubzoneNameMustBeUniqueSameZone {
            get {
                return ResourceManager.GetString("SubzoneNameMustBeUniqueSameZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible completar la acción. El nombre ingresado ya se encuentra registrado en el sistema..
        /// </summary>
        internal static string ZoneNameMustBeUnique {
            get {
                return ResourceManager.GetString("ZoneNameMustBeUnique", resourceCulture);
            }
        }
    }
}
